# Generated by Django 4.1.4 on 2022-12-14 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffee",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coffee",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
