# Generated by Django 4.1.4 on 2022-12-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0002_coffee_created_at_coffee_update_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("reviewer", models.TextField()),
            ],
        ),
    ]
